#!/bin/bash
# Script to create unique userids from a list of user names
# CS 370, Fall 2012


inputfile=$1


# 0. Remove any temporary files from previous runs of the script.
#    This is essential during script testing.

# 1. Create firstn from $inputfile

echo "1. Extracting 1st letter of first name to firstn "
cut -d " " -f 2 $inputfile | cut -c 1 | tr A-Z a-z > firstn

# 2. Create lastn from $inputfile with all special characters removed

echo "2. Removing special characters and extracting up to 7 letters"
echo " of a user's last name from input file to lastn "
cut -d "," -f 1 $inputfile | sed "s/[^A-Za-z]//g" | cut -c 1-7 | tr A-Z a-z > lastn

# 3. Create first draft userids file from firstn and lastn > ids.1st'.
#    It contains userids in this format:
#
#     jabraham
#     tabraham
#     jabraham
#     jabrams
#     dabrams
#     jabrams
#
# We want to keep the ids.1st file in the same order as $inpufile
# since we want to be able to paste the ids file and $inputfile
# together at some point, like this (after duplicate ids have been
# dealt with):
#
#     Abraham, Jesse :jabraha1
#     Abrahamsen, Theresa :tabraham
#     Abrahamson, Jonathan :jabraha2
#     Abrams, Jenelle :jabrams1
#     Abrams, Dana :dabrams
#     Abrams, Jessica :jabrams2

echo "3. Creating first draft userids file called ids.1st "
paste -d "" firstn lastn > ids.1st

# 4. Create list of the duplicated ids in ids.1st > duplids'.
#    We'll use duplids as a lookup table.  A portion of duplids is
#    shown below:
#
#     jabraham
#     tabraham
#     jabrams
#     dabrams

echo "4. Creating a list of duplicate ids from first draft called dupids "
cat ids.1st | sort | uniq -d | sed "s/\n/ /g" > dupids

# 5. Append userids from ids.1st to ids.2nd.
#    If a userid is duplicated, attach appropriate numbers to them
#    and append to ids.2nd.
#
#    Here, grep is your friend. But, be sure to do WHOLE WORD grep. 
#
#    For each userid in ids.1st,
#       grep for the userid in duplids from Step 4.
#
#       If grep didn't find the userid in duplids, it's unique, so
#           just append it straightaway to ids.2nd
#
#       Else, (if grep did find the userid in duplids)
#           attach a number to the userid starting at number=1, making
#           sure the userid remains no more than 8 chars.
#
#           grep for the numbered userid in ids.2nd.
#
#           If grep finds that the numbered userid is already in
#           ids.2nd, increment the number by 1, and grep for the new
#           numbered userid in ids.2nd.  REPEAT until grep does not
#           find the numbered userid in ids.2nd.
#
#           Append the numbered userid to ids.2nd.
#
#
# After this, ids.2nd will look like this (the original order of
# ids.1st is preserved):
#
#     jabraha1
#     tabraham
#     jabraha2
#     jabrams1
#     dabrams
#     jabrams2

echo "5. Finding and appending numbers to duplicates in ids.1st and creating ids.2nd "
oldUser="blank"
idsChecked=0
number=1
for each in `cat ids.1st`
do
	newUser=$(echo $each)
	if [ $newUser == $oldUser ]; then
		number=$((number+1))
	else
		number=1
	fi

	if [ $idsChecked -eq 100 ] ; then
		echo -n "."
		idsChecked=1
	fi

	grep -w -q $each dupids
	if [ $? -eq "1" ]; then
#		echo "Not a dup"
		echo $each >> ids.2nd
		oldUser=$(echo $each)		
	else
#		echo "This is a dup"
		if [ $number -gt 9 ]; then
#			echo "Double digits"
			tempUser=$(echo $each | cut -c 1-6)
			tempID=$(echo $tempUser$number)

			grep -w -q $tempID ids.2nd
			if [ $? -eq "0" ]; then
				while [ $? -eq "0" ] 
				do
					number=$((number+1))
					tempID=$(echo $tempUser$number)
					grep -w -q $tempID ids.2nd
				done
				echo $tempID >> ids.2nd
			else
				echo $tempID >> ids.2nd
			fi

			oldUser=$(echo $each)
		else
#			echo "Single digits"
			tempUser=$(echo $each | cut -c 1-7)
			tempID=$(echo $tempUser$number)

			grep -w -q $tempID ids.2nd
			if [ $? -eq "0" ]; then
				while [ $? -eq "0" ] 
				do
					number=$((number+1))
					tempID=$(echo $tempUser$number)
					grep -w -q $tempID ids.2nd
				done
				echo $tempID >> ids.2nd
			else
				echo $tempID >> ids.2nd
			fi

			oldUser=$(echo $each)
		fi
	fi

	idsChecked=$((idsChecked+1))

done

# 6. Double check ids.2nd for any userid duplications.
#    The same uniq option used to create duplids (step 4) should
#    work.

echo " "
echo "6. Double checking ids.2nd for any duplicates "
cat ids.2nd | sort | uniq -d | sed "s/\n/ /g" > dupids.2nd

# 7. Paste ids.2nd to $inputfile > ids.final

echo "7. Creating final file called ids.final and removing temporary files"
paste -d ":" $inputfile ids.2nd > ids.final
rm firstn 
rm lastn 
rm ids.1st
rm ids.2nd
rm dupids
rm dupids.2nd
echo "Done "




